// Code generated by MockGen. DO NOT EDIT.

// Package mocks implements mock objects for testing.
package mocks

import (
	"context"
	"reflect"

	"jiufang/internal/model/audit"

	"github.com/golang/mock/gomock"
)

// MockOperationLogRepository is a mock of OperationLogRepositoryInterface.
type MockOperationLogRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOperationLogRepositoryMockRecorder
}

// MockOperationLogRepositoryMockRecorder is the mock recorder for MockOperationLogRepository.
type MockOperationLogRepositoryMockRecorder struct {
	mock *MockOperationLogRepository
}

// NewMockOperationLogRepository creates a new mock instance.
func NewMockOperationLogRepository(ctrl *gomock.Controller) *MockOperationLogRepository {
	mock := &MockOperationLogRepository{ctrl: ctrl}
	mock.recorder = &MockOperationLogRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOperationLogRepository) EXPECT() *MockOperationLogRepositoryMockRecorder {
	return m.recorder
}

// Create mocks the Create method.
func (m *MockOperationLogRepository) Create(ctx context.Context, log *audit.OperationLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, log)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOperationLogRepositoryMockRecorder) Create(ctx, log interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOperationLogRepository)(nil).Create), ctx, log)
}

// GetByID mocks the GetByID method.
func (m *MockOperationLogRepository) GetByID(ctx context.Context, id uint) (*audit.OperationLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*audit.OperationLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockOperationLogRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockOperationLogRepository)(nil).GetByID), ctx, id)
}

// GetBySnowflakeID mocks the GetBySnowflakeID method.
func (m *MockOperationLogRepository) GetBySnowflakeID(ctx context.Context, snowflakeID int64) (*audit.OperationLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySnowflakeID", ctx, snowflakeID)
	ret0, _ := ret[0].(*audit.OperationLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySnowflakeID indicates an expected call of GetBySnowflakeID.
func (mr *MockOperationLogRepositoryMockRecorder) GetBySnowflakeID(ctx, snowflakeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySnowflakeID", reflect.TypeOf((*MockOperationLogRepository)(nil).GetBySnowflakeID), ctx, snowflakeID)
}

// List mocks the List method.
func (m *MockOperationLogRepository) List(ctx context.Context, offset, limit int, userID int64, operationType string, startTime, endTime string) ([]audit.OperationLog, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, offset, limit, userID, operationType, startTime, endTime)
	ret0, _ := ret[0].([]audit.OperationLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockOperationLogRepositoryMockRecorder) List(ctx, offset, limit, userID, operationType, startTime, endTime interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockOperationLogRepository)(nil).List), ctx, offset, limit, userID, operationType, startTime, endTime)
}

// GetByUsername mocks the GetByUsername method.
func (m *MockOperationLogRepository) GetByUsername(ctx context.Context, username string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsername", ctx, username)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUsername indicates an expected call of GetByUsername.
func (mr *MockOperationLogRepositoryMockRecorder) GetByUsername(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsername", reflect.TypeOf((*MockOperationLogRepository)(nil).GetByUsername), ctx, username)
}