// Code generated by MockGen. DO NOT EDIT.
// Package mocks provides mock implementations for repository interfaces.

package mocks

import (
	"context"
	"reflect"

	"jiufang/internal/model/feedback"

	"github.com/golang/mock/gomock"
)

// MockFeedbackRepository is a mock of FeedbackRepositoryInterface.
type MockFeedbackRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFeedbackRepositoryMockRecorder
}

// MockFeedbackRepositoryMockRecorder is the mock recorder for MockFeedbackRepository.
type MockFeedbackRepositoryMockRecorder struct {
	mock *MockFeedbackRepository
}

// NewMockFeedbackRepository creates a new mock instance.
func NewMockFeedbackRepository(ctrl *gomock.Controller) *MockFeedbackRepository {
	mock := &MockFeedbackRepository{ctrl: ctrl}
	mock.recorder = &MockFeedbackRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedbackRepository) EXPECT() *MockFeedbackRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFeedbackRepository) Create(ctx context.Context, feedback *feedback.Feedback) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, feedback)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockFeedbackRepositoryMockRecorder) Create(ctx, feedback interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFeedbackRepository)(nil).Create), ctx, feedback)
}

// GetByID mocks base method.
func (m *MockFeedbackRepository) GetByID(ctx context.Context, id uint) (*feedback.Feedback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*feedback.Feedback)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockFeedbackRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockFeedbackRepository)(nil).GetByID), ctx, id)
}

// GetBySnowflakeID mocks base method.
func (m *MockFeedbackRepository) GetBySnowflakeID(ctx context.Context, snowflakeID int64) (*feedback.Feedback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySnowflakeID", ctx, snowflakeID)
	ret0, _ := ret[0].(*feedback.Feedback)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySnowflakeID indicates an expected call of GetBySnowflakeID.
func (mr *MockFeedbackRepositoryMockRecorder) GetBySnowflakeID(ctx, snowflakeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySnowflakeID", reflect.TypeOf((*MockFeedbackRepository)(nil).GetBySnowflakeID), ctx, snowflakeID)
}

// GetByQueryRecordID mocks base method.
func (m *MockFeedbackRepository) GetByQueryRecordID(ctx context.Context, queryRecordID int64) (*feedback.Feedback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByQueryRecordID", ctx, queryRecordID)
	ret0, _ := ret[0].(*feedback.Feedback)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByQueryRecordID indicates an expected call of GetByQueryRecordID.
func (mr *MockFeedbackRepositoryMockRecorder) GetByQueryRecordID(ctx, queryRecordID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByQueryRecordID", reflect.TypeOf((*MockFeedbackRepository)(nil).GetByQueryRecordID), ctx, queryRecordID)
}

// GetByUserID mocks base method.
func (m *MockFeedbackRepository) GetByUserID(ctx context.Context, userID int64, offset, limit int) ([]feedback.Feedback, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID, offset, limit)
	ret0, _ := ret[0].([]feedback.Feedback)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockFeedbackRepositoryMockRecorder) GetByUserID(ctx, userID, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockFeedbackRepository)(nil).GetByUserID), ctx, userID, offset, limit)
}

// List mocks base method.
func (m *MockFeedbackRepository) List(ctx context.Context, offset, limit int, userID int64, rating string) ([]feedback.Feedback, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, offset, limit, userID, rating)
	ret0, _ := ret[0].([]feedback.Feedback)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockFeedbackRepositoryMockRecorder) List(ctx, offset, limit, userID, rating interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockFeedbackRepository)(nil).List), ctx, offset, limit, userID, rating)
}

// IsFeedbackExists mocks base method.
func (m *MockFeedbackRepository) IsFeedbackExists(ctx context.Context, queryRecordID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFeedbackExists", ctx, queryRecordID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsFeedbackExists indicates an expected call of IsFeedbackExists.
func (mr *MockFeedbackRepositoryMockRecorder) IsFeedbackExists(ctx, queryRecordID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFeedbackExists", reflect.TypeOf((*MockFeedbackRepository)(nil).IsFeedbackExists), ctx, queryRecordID)
}
