// Code generated by MockGen. DO NOT EDIT.

// Package mocks implements mock objects for testing.
package mocks

import (
	"context"
	"reflect"
	"time"

	"jiufang/internal/model/report"

	"github.com/golang/mock/gomock"
)

// MockAlertRepository is a mock of AlertRepositoryInterface.
type MockAlertRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAlertRepositoryMockRecorder
}

// MockAlertRepositoryMockRecorder is the mock recorder for MockAlertRepository.
type MockAlertRepositoryMockRecorder struct {
	mock *MockAlertRepository
}

// NewMockAlertRepository creates a new mock instance.
func NewMockAlertRepository(ctrl *gomock.Controller) *MockAlertRepository {
	mock := &MockAlertRepository{ctrl: ctrl}
	mock.recorder = &MockAlertRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAlertRepository) EXPECT() *MockAlertRepositoryMockRecorder {
	return m.recorder
}

// Create mocks the Create method.
func (m *MockAlertRepository) Create(ctx context.Context, alert *report.Alert) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, alert)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAlertRepositoryMockRecorder) Create(ctx, alert interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAlertRepository)(nil).Create), ctx, alert)
}

// GetByID mocks the GetByID method.
func (m *MockAlertRepository) GetByID(ctx context.Context, id uint) (*report.Alert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*report.Alert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAlertRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAlertRepository)(nil).GetByID), ctx, id)
}

// GetBySnowflakeID mocks the GetBySnowflakeID method.
func (m *MockAlertRepository) GetBySnowflakeID(ctx context.Context, snowflakeID int64) (*report.Alert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySnowflakeID", ctx, snowflakeID)
	ret0, _ := ret[0].(*report.Alert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySnowflakeID indicates an expected call of GetBySnowflakeID.
func (mr *MockAlertRepositoryMockRecorder) GetBySnowflakeID(ctx, snowflakeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySnowflakeID", reflect.TypeOf((*MockAlertRepository)(nil).GetBySnowflakeID), ctx, snowflakeID)
}

// List mocks the List method.
func (m *MockAlertRepository) List(ctx context.Context, offset, limit int, name string, status string) ([]report.Alert, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, offset, limit, name, status)
	ret0, _ := ret[0].([]report.Alert)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockAlertRepositoryMockRecorder) List(ctx, offset, limit, name, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAlertRepository)(nil).List), ctx, offset, limit, name, status)
}

// Update mocks the Update method.
func (m *MockAlertRepository) Update(ctx context.Context, snowflakeID int64, updates map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, snowflakeID, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAlertRepositoryMockRecorder) Update(ctx, snowflakeID, updates interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAlertRepository)(nil).Update), ctx, snowflakeID, updates)
}

// Delete mocks the Delete method.
func (m *MockAlertRepository) Delete(ctx context.Context, snowflakeID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, snowflakeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAlertRepositoryMockRecorder) Delete(ctx, snowflakeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAlertRepository)(nil).Delete), ctx, snowflakeID)
}

// GetActiveAlerts mocks the GetActiveAlerts method.
func (m *MockAlertRepository) GetActiveAlerts(ctx context.Context) ([]report.Alert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveAlerts", ctx)
	ret0, _ := ret[0].([]report.Alert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveAlerts indicates an expected call of GetActiveAlerts.
func (mr *MockAlertRepositoryMockRecorder) GetActiveAlerts(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveAlerts", reflect.TypeOf((*MockAlertRepository)(nil).GetActiveAlerts), ctx)
}

// UpdateLastTriggeredAt mocks the UpdateLastTriggeredAt method.
func (m *MockAlertRepository) UpdateLastTriggeredAt(ctx context.Context, snowflakeID int64, triggeredAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastTriggeredAt", ctx, snowflakeID, triggeredAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastTriggeredAt indicates an expected call of UpdateLastTriggeredAt.
func (mr *MockAlertRepositoryMockRecorder) UpdateLastTriggeredAt(ctx, snowflakeID, triggeredAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastTriggeredAt", reflect.TypeOf((*MockAlertRepository)(nil).UpdateLastTriggeredAt), ctx, snowflakeID, triggeredAt)
}
