// Code generated by MockGen. DO NOT EDIT.
// Source: jiufang/internal/repository/interfaces.go

package mocks

import (
	"context"
	"reflect"

	"github.com/golang/mock/gomock"

	"jiufang/internal/model/export"
)

// MockExportRecordRepositoryInterface is a mock of ExportRecordRepositoryInterface.
type MockExportRecordRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockExportRecordRepositoryInterfaceMockRecorder
}

// MockExportRecordRepositoryInterfaceMockRecorder is the mock recorder for MockExportRecordRepositoryInterface.
type MockExportRecordRepositoryInterfaceMockRecorder struct {
	mock *MockExportRecordRepositoryInterface
}

// NewMockExportRecordRepositoryInterface creates a new mock instance.
func NewMockExportRecordRepositoryInterface(ctrl *gomock.Controller) *MockExportRecordRepositoryInterface {
	mock := &MockExportRecordRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockExportRecordRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExportRecordRepositoryInterface) EXPECT() *MockExportRecordRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CreateExportRecord mocks base method.
func (m *MockExportRecordRepositoryInterface) CreateExportRecord(ctx context.Context, record *export.ExportRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateExportRecord", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateExportRecord indicates an expected call of CreateExportRecord.
func (mr *MockExportRecordRepositoryInterfaceMockRecorder) CreateExportRecord(ctx, record interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExportRecord", reflect.TypeOf((*MockExportRecordRepositoryInterface)(nil).CreateExportRecord), ctx, record)
}

// GetExportRecordByID mocks base method.
func (m *MockExportRecordRepositoryInterface) GetExportRecordByID(ctx context.Context, id uint) (*export.ExportRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExportRecordByID", ctx, id)
	ret0, _ := ret[0].(*export.ExportRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExportRecordByID indicates an expected call of GetExportRecordByID.
func (mr *MockExportRecordRepositoryInterfaceMockRecorder) GetExportRecordByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExportRecordByID", reflect.TypeOf((*MockExportRecordRepositoryInterface)(nil).GetExportRecordByID), ctx, id)
}

// GetExportRecordBySnowflakeID mocks base method.
func (m *MockExportRecordRepositoryInterface) GetExportRecordBySnowflakeID(ctx context.Context, snowflakeID int64) (*export.ExportRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExportRecordBySnowflakeID", ctx, snowflakeID)
	ret0, _ := ret[0].(*export.ExportRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExportRecordBySnowflakeID indicates an expected call of GetExportRecordBySnowflakeID.
func (mr *MockExportRecordRepositoryInterfaceMockRecorder) GetExportRecordBySnowflakeID(ctx, snowflakeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExportRecordBySnowflakeID", reflect.TypeOf((*MockExportRecordRepositoryInterface)(nil).GetExportRecordBySnowflakeID), ctx, snowflakeID)
}

// GetExportRecordsByUserID mocks base method.
func (m *MockExportRecordRepositoryInterface) GetExportRecordsByUserID(ctx context.Context, userID int64, offset, limit int) ([]export.ExportRecord, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExportRecordsByUserID", ctx, userID, offset, limit)
	ret0, _ := ret[0].([]export.ExportRecord)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetExportRecordsByUserID indicates an expected call of GetExportRecordsByUserID.
func (mr *MockExportRecordRepositoryInterfaceMockRecorder) GetExportRecordsByUserID(ctx, userID, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExportRecordsByUserID", reflect.TypeOf((*MockExportRecordRepositoryInterface)(nil).GetExportRecordsByUserID), ctx, userID, offset, limit)
}