// Code generated by MockGen. DO NOT EDIT.
// Package mocks provides mock implementations for service interfaces.

package mocks

import (
	"context"
	"reflect"

	"jiufang/internal/model/report"

	"github.com/golang/mock/gomock"
)

// MockPushAppService is a mock of PushAppServiceInterface.
type MockPushAppService struct {
	ctrl     *gomock.Controller
	recorder *MockPushAppServiceMockRecorder
}

// MockPushAppServiceMockRecorder is the mock recorder for MockPushAppService.
type MockPushAppServiceMockRecorder struct {
	mock *MockPushAppService
}

// NewMockPushAppService creates a new mock instance.
func NewMockPushAppService(ctrl *gomock.Controller) *MockPushAppService {
	mock := &MockPushAppService{ctrl: ctrl}
	mock.recorder = &MockPushAppServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPushAppService) EXPECT() *MockPushAppServiceMockRecorder {
	return m.recorder
}

// ExecuteAndPushReport mocks base method.
func (m *MockPushAppService) ExecuteAndPushReport(ctx context.Context, scheduledReport *report.ScheduledReport) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteAndPushReport", ctx, scheduledReport)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteAndPushReport indicates an expected call of ExecuteAndPushReport.
func (mr *MockPushAppServiceMockRecorder) ExecuteAndPushReport(ctx, scheduledReport interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteAndPushReport", reflect.TypeOf((*MockPushAppService)(nil).ExecuteAndPushReport), ctx, scheduledReport)
}

// RetryFailedPushes mocks base method.
func (m *MockPushAppService) RetryFailedPushes(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetryFailedPushes", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RetryFailedPushes indicates an expected call of RetryFailedPushes.
func (mr *MockPushAppServiceMockRecorder) RetryFailedPushes(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetryFailedPushes", reflect.TypeOf((*MockPushAppService)(nil).RetryFailedPushes), ctx)
}
