// Code generated by MockGen. DO NOT EDIT.
// Source: jiufang/internal/infrastructure/erp/connector.go

package mocks

import (
	"context"
	"reflect"
	"time"

	"github.com/golang/mock/gomock"
	"gorm.io/gorm"

	"jiufang/internal/infrastructure/erp"
)

// MockERPReader is a mock of ERPReaderInterface.
type MockERPReader struct {
	ctrl     *gomock.Controller
	recorder *MockERPReaderMockRecorder
}

// MockERPReaderMockRecorder is the mock recorder for MockERPReader.
type MockERPReaderMockRecorder struct {
	mock *MockERPReader
}

// NewMockERPReader creates a new mock instance.
func NewMockERPReader(ctrl *gomock.Controller) *MockERPReader {
	mock := &MockERPReader{ctrl: ctrl}
	mock.recorder = &MockERPReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockERPReader) EXPECT() *MockERPReaderMockRecorder {
	return m.recorder
}

// Query mocks base method.
func (m *MockERPReader) Query(ctx context.Context, sql string, args ...interface{}) ([]map[string]interface{}, error) {
	ret := m.ctrl.Call(m, "Query", ctx, sql, args)
	ret0, _ := ret[0].([]map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockERPReaderMockRecorder) Query(ctx, sql interface{}, args ...interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockERPReader)(nil).Query), ctx, sql, args)
}

// QueryWithLimit mocks base method.
func (m *MockERPReader) QueryWithLimit(ctx context.Context, sql string, limit int) ([]map[string]interface{}, error) {
	ret := m.ctrl.Call(m, "QueryWithLimit", ctx, sql, limit)
	ret0, _ := ret[0].([]map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryWithLimit indicates an expected call of QueryWithLimit.
func (mr *MockERPReaderMockRecorder) QueryWithLimit(ctx, sql, limit interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryWithLimit", reflect.TypeOf((*MockERPReader)(nil).QueryWithLimit), ctx, sql, limit)
}

// QueryWithTimeout mocks base method.
func (m *MockERPReader) QueryWithTimeout(ctx context.Context, sql string, timeout time.Duration) ([]map[string]interface{}, error) {
	ret := m.ctrl.Call(m, "QueryWithTimeout", ctx, sql, timeout)
	ret0, _ := ret[0].([]map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryWithTimeout indicates an expected call of QueryWithTimeout.
func (mr *MockERPReaderMockRecorder) QueryWithTimeout(ctx, sql, timeout interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryWithTimeout", reflect.TypeOf((*MockERPReader)(nil).QueryWithTimeout), ctx, sql, timeout)
}

// GetTableSchema mocks base method.
func (m *MockERPReader) GetTableSchema(ctx context.Context, tableName string) (*erp.TableSchema, error) {
	ret := m.ctrl.Call(m, "GetTableSchema", ctx, tableName)
	ret0, _ := ret[0].(*erp.TableSchema)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTableSchema indicates an expected call of GetTableSchema.
func (mr *MockERPReaderMockRecorder) GetTableSchema(ctx, tableName interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTableSchema", reflect.TypeOf((*MockERPReader)(nil).GetTableSchema), ctx, tableName)
}

// GetTableList mocks base method.
func (m *MockERPReader) GetTableList(ctx context.Context) ([]string, error) {
	ret := m.ctrl.Call(m, "GetTableList", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTableList indicates an expected call of GetTableList.
func (mr *MockERPReaderMockRecorder) GetTableList(ctx interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTableList", reflect.TypeOf((*MockERPReader)(nil).GetTableList), ctx)
}

// ValidateSQL mocks base method.
func (m *MockERPReader) ValidateSQL(sql string) error {
	ret := m.ctrl.Call(m, "ValidateSQL", sql)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateSQL indicates an expected call of ValidateSQL.
func (mr *MockERPReaderMockRecorder) ValidateSQL(sql interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSQL", reflect.TypeOf((*MockERPReader)(nil).ValidateSQL), sql)
}

// IsReadOnly mocks base method.
func (m *MockERPReader) IsReadOnly(sql string) bool {
	ret := m.ctrl.Call(m, "IsReadOnly", sql)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsReadOnly indicates an expected call of IsReadOnly.
func (mr *MockERPReaderMockRecorder) IsReadOnly(sql interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsReadOnly", reflect.TypeOf((*MockERPReader)(nil).IsReadOnly), sql)
}

// GetDB mocks base method.
func (m *MockERPReader) GetDB() *gorm.DB {
	ret := m.ctrl.Call(m, "GetDB")
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// GetDB indicates an expected call of GetDB.
func (mr *MockERPReaderMockRecorder) GetDB() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDB", reflect.TypeOf((*MockERPReader)(nil).GetDB))
}