// Code generated by MockGen. DO NOT EDIT.
// Package mocks provides mock implementations for repository interfaces.

package mocks

import (
	"context"
	"reflect"

	"jiufang/internal/model/report"

	"github.com/golang/mock/gomock"
)

// MockReportRepository is a mock of ReportRepositoryInterface.
type MockReportRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReportRepositoryMockRecorder
}

// MockReportRepositoryMockRecorder is the mock recorder for MockReportRepository.
type MockReportRepositoryMockRecorder struct {
	mock *MockReportRepository
}

// NewMockReportRepository creates a new mock instance.
func NewMockReportRepository(ctrl *gomock.Controller) *MockReportRepository {
	mock := &MockReportRepository{ctrl: ctrl}
	mock.recorder = &MockReportRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportRepository) EXPECT() *MockReportRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockReportRepository) Create(ctx context.Context, scheduledReport *report.ScheduledReport) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, scheduledReport)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockReportRepositoryMockRecorder) Create(ctx, scheduledReport interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockReportRepository)(nil).Create), ctx, scheduledReport)
}

// GetByID mocks base method.
func (m *MockReportRepository) GetByID(ctx context.Context, id uint) (*report.ScheduledReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*report.ScheduledReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockReportRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockReportRepository)(nil).GetByID), ctx, id)
}

// GetBySnowflakeID mocks base method.
func (m *MockReportRepository) GetBySnowflakeID(ctx context.Context, snowflakeID int64) (*report.ScheduledReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySnowflakeID", ctx, snowflakeID)
	ret0, _ := ret[0].(*report.ScheduledReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySnowflakeID indicates an expected call of GetBySnowflakeID.
func (mr *MockReportRepositoryMockRecorder) GetBySnowflakeID(ctx, snowflakeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySnowflakeID", reflect.TypeOf((*MockReportRepository)(nil).GetBySnowflakeID), ctx, snowflakeID)
}

// List mocks base method.
func (m *MockReportRepository) List(ctx context.Context, offset, limit int, name, status string) ([]report.ScheduledReport, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, offset, limit, name, status)
	ret0, _ := ret[0].([]report.ScheduledReport)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockReportRepositoryMockRecorder) List(ctx, offset, limit, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockReportRepository)(nil).List), ctx, offset, limit, status)
}

// Update mocks base method.
func (m *MockReportRepository) Update(ctx context.Context, snowflakeID int64, updates map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, snowflakeID, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockReportRepositoryMockRecorder) Update(ctx, snowflakeID, updates interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockReportRepository)(nil).Update), ctx, snowflakeID, updates)
}

// Delete mocks base method.
func (m *MockReportRepository) Delete(ctx context.Context, snowflakeID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, snowflakeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockReportRepositoryMockRecorder) Delete(ctx, snowflakeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockReportRepository)(nil).Delete), ctx, snowflakeID)
}

// GetActiveReports mocks base method.
func (m *MockReportRepository) GetActiveReports(ctx context.Context) ([]report.ScheduledReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveReports", ctx)
	ret0, _ := ret[0].([]report.ScheduledReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveReports indicates an expected call of GetActiveReports.
func (mr *MockReportRepositoryMockRecorder) GetActiveReports(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveReports", reflect.TypeOf((*MockReportRepository)(nil).GetActiveReports), ctx)
}

// CreatePushRecord mocks base method.
func (m *MockReportRepository) CreatePushRecord(ctx context.Context, pushRecord *report.PushRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePushRecord", ctx, pushRecord)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePushRecord indicates an expected call of CreatePushRecord.
func (mr *MockReportRepositoryMockRecorder) CreatePushRecord(ctx, pushRecord interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePushRecord", reflect.TypeOf((*MockReportRepository)(nil).CreatePushRecord), ctx, pushRecord)
}

// GetPushRecordByID mocks base method.
func (m *MockReportRepository) GetPushRecordByID(ctx context.Context, id uint) (*report.PushRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPushRecordByID", ctx, id)
	ret0, _ := ret[0].(*report.PushRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPushRecordByID indicates an expected call of GetPushRecordByID.
func (mr *MockReportRepositoryMockRecorder) GetPushRecordByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPushRecordByID", reflect.TypeOf((*MockReportRepository)(nil).GetPushRecordByID), ctx, id)
}

// GetPushRecordBySnowflakeID mocks base method.
func (m *MockReportRepository) GetPushRecordBySnowflakeID(ctx context.Context, snowflakeID int64) (*report.PushRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPushRecordBySnowflakeID", ctx, snowflakeID)
	ret0, _ := ret[0].(*report.PushRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPushRecordBySnowflakeID indicates an expected call of GetPushRecordBySnowflakeID.
func (mr *MockReportRepositoryMockRecorder) GetPushRecordBySnowflakeID(ctx, snowflakeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPushRecordBySnowflakeID", reflect.TypeOf((*MockReportRepository)(nil).GetPushRecordBySnowflakeID), ctx, snowflakeID)
}

// GetPushRecordsByReportID mocks base method.
func (m *MockReportRepository) GetPushRecordsByReportID(ctx context.Context, reportID int64, offset, limit int, pushStatus string) ([]report.PushRecord, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPushRecordsByReportID", ctx, reportID, offset, limit, pushStatus)
	ret0, _ := ret[0].([]report.PushRecord)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPushRecordsByReportID indicates an expected call of GetPushRecordsByReportID.
func (mr *MockReportRepositoryMockRecorder) GetPushRecordsByReportID(ctx, reportID, offset, limit, pushStatus interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPushRecordsByReportID", reflect.TypeOf((*MockReportRepository)(nil).GetPushRecordsByReportID), ctx, reportID, offset, limit, pushStatus)
}

// ListPushRecords mocks base method.
func (m *MockReportRepository) ListPushRecords(ctx context.Context, offset, limit int, pushType, pushStatus, startTime, endTime string) ([]report.PushRecord, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPushRecords", ctx, offset, limit, pushType, pushStatus, startTime, endTime)
	ret0, _ := ret[0].([]report.PushRecord)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListPushRecords indicates an expected call of ListPushRecords.
func (mr *MockReportRepositoryMockRecorder) ListPushRecords(ctx, offset, limit, pushType, pushStatus, startTime, endTime interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPushRecords", reflect.TypeOf((*MockReportRepository)(nil).ListPushRecords), ctx, offset, limit, pushType, pushStatus, startTime, endTime)
}

// UpdatePushRecord mocks base method.
func (m *MockReportRepository) UpdatePushRecord(ctx context.Context, snowflakeID int64, updates map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePushRecord", ctx, snowflakeID, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePushRecord indicates an expected call of UpdatePushRecord.
func (mr *MockReportRepositoryMockRecorder) UpdatePushRecord(ctx, snowflakeID, updates interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePushRecord", reflect.TypeOf((*MockReportRepository)(nil).UpdatePushRecord), ctx, snowflakeID, updates)
}
