// Code generated by MockGen. DO NOT EDIT.
// Source: jiufang/internal/infrastructure/llm/client.go

package mocks

import (
	"context"
	"reflect"

	"github.com/cloudwego/eino/schema"
	"github.com/golang/mock/gomock"
)

// MockLLMClient is a mock of LLMClientInterface.
type MockLLMClient struct {
	ctrl     *gomock.Controller
	recorder *MockLLMClientMockRecorder
}

// MockLLMClientMockRecorder is the mock recorder for MockLLMClient.
type MockLLMClientMockRecorder struct {
	mock *MockLLMClient
}

// NewMockLLMClient creates a new mock instance.
func NewMockLLMClient(ctrl *gomock.Controller) *MockLLMClient {
	mock := &MockLLMClient{ctrl: ctrl}
	mock.recorder = &MockLLMClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMClient) EXPECT() *MockLLMClientMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockLLMClient) Generate(ctx context.Context, prompt string) (string, error) {
	ret := m.ctrl.Call(m, "Generate", ctx, prompt)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockLLMClientMockRecorder) Generate(ctx, prompt interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockLLMClient)(nil).Generate), ctx, prompt)
}

// GenerateWithMessages mocks base method.
func (m *MockLLMClient) GenerateWithMessages(ctx context.Context, messages []*schema.Message) (string, error) {
	ret := m.ctrl.Call(m, "GenerateWithMessages", ctx, messages)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateWithMessages indicates an expected call of GenerateWithMessages.
func (mr *MockLLMClientMockRecorder) GenerateWithMessages(ctx, messages interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateWithMessages", reflect.TypeOf((*MockLLMClient)(nil).GenerateWithMessages), ctx, messages)
}

// GenerateWithSchema mocks base method.
func (m *MockLLMClient) GenerateWithSchema(ctx context.Context, prompt string, schema interface{}) (interface{}, error) {
	ret := m.ctrl.Call(m, "GenerateWithSchema", ctx, prompt, schema)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateWithSchema indicates an expected call of GenerateWithSchema.
func (mr *MockLLMClientMockRecorder) GenerateWithSchema(ctx, prompt, schema interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateWithSchema", reflect.TypeOf((*MockLLMClient)(nil).GenerateWithSchema), ctx, prompt, schema)
}

// Stream mocks base method.
func (m *MockLLMClient) Stream(ctx context.Context, prompt string) (*schema.StreamReader[*schema.Message], error) {
	ret := m.ctrl.Call(m, "Stream", ctx, prompt)
	ret0, _ := ret[0].(*schema.StreamReader[*schema.Message])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stream indicates an expected call of Stream.
func (mr *MockLLMClientMockRecorder) Stream(ctx, prompt interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stream", reflect.TypeOf((*MockLLMClient)(nil).Stream), ctx, prompt)
}

// StreamWithMessages mocks base method.
func (m *MockLLMClient) StreamWithMessages(ctx context.Context, messages []*schema.Message) (*schema.StreamReader[*schema.Message], error) {
	ret := m.ctrl.Call(m, "StreamWithMessages", ctx, messages)
	ret0, _ := ret[0].(*schema.StreamReader[*schema.Message])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamWithMessages indicates an expected call of StreamWithMessages.
func (mr *MockLLMClientMockRecorder) StreamWithMessages(ctx, messages interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamWithMessages", reflect.TypeOf((*MockLLMClient)(nil).StreamWithMessages), ctx, messages)
}

// GetName mocks base method.
func (m *MockLLMClient) GetName() string {
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockLLMClientMockRecorder) GetName() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockLLMClient)(nil).GetName))
}
