// Code generated by MockGen. DO NOT EDIT.
// Source: jiufang/internal/service/export_app_service.go

package mocks

import (
	"context"
	"reflect"

	"github.com/golang/mock/gomock"

	"jiufang/internal/model/export"
)

// MockExportAppService is a mock of ExportAppService.
type MockExportAppService struct {
	ctrl     *gomock.Controller
	recorder *MockExportAppServiceMockRecorder
}

// MockExportAppServiceMockRecorder is the mock recorder for MockExportAppService.
type MockExportAppServiceMockRecorder struct {
	mock *MockExportAppService
}

// NewMockExportAppService creates a new mock instance.
func NewMockExportAppService(ctrl *gomock.Controller) *MockExportAppService {
	mock := &MockExportAppService{ctrl: ctrl}
	mock.recorder = &MockExportAppServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExportAppService) EXPECT() *MockExportAppServiceMockRecorder {
	return m.recorder
}

// ExportQueryResult mocks base method.
func (m *MockExportAppService) ExportQueryResult(ctx context.Context, userID int64, req *export.ExportRequest) (*export.ExportResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportQueryResult", ctx, userID, req)
	ret0, _ := ret[0].(*export.ExportResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExportQueryResult indicates an expected call of ExportQueryResult.
func (mr *MockExportAppServiceMockRecorder) ExportQueryResult(ctx, userID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportQueryResult", reflect.TypeOf((*MockExportAppService)(nil).ExportQueryResult), ctx, userID, req)
}

// GetExportRecordList mocks base method.
func (m *MockExportAppService) GetExportRecordList(ctx context.Context, userID int64, page, pageSize int) ([]export.ExportRecord, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExportRecordList", ctx, userID, page, pageSize)
	ret0, _ := ret[0].([]export.ExportRecord)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetExportRecordList indicates an expected call of GetExportRecordList.
func (mr *MockExportAppServiceMockRecorder) GetExportRecordList(ctx, userID, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExportRecordList", reflect.TypeOf((*MockExportAppService)(nil).GetExportRecordList), ctx, userID, page, pageSize)
}