// Code generated by MockGen. DO NOT EDIT.
// Package mocks provides mock implementations for service interfaces.

package mocks

import (
	"context"
	"reflect"

	"jiufang/internal/model/report"

	"github.com/golang/mock/gomock"
)

// MockReportService is a mock of ReportServiceInterface.
type MockReportService struct {
	ctrl     *gomock.Controller
	recorder *MockReportServiceMockRecorder
}

// MockReportServiceMockRecorder is the mock recorder for MockReportService.
type MockReportServiceMockRecorder struct {
	mock *MockReportService
}

// NewMockReportService creates a new mock instance.
func NewMockReportService(ctrl *gomock.Controller) *MockReportService {
	mock := &MockReportService{ctrl: ctrl}
	mock.recorder = &MockReportServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportService) EXPECT() *MockReportServiceMockRecorder {
	return m.recorder
}

// CreateReport mocks base method.
func (m *MockReportService) CreateReport(ctx context.Context, req *report.CreateReportRequest) (*report.ScheduledReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReport", ctx, req)
	ret0, _ := ret[0].(*report.ScheduledReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateReport indicates an expected call of CreateReport.
func (mr *MockReportServiceMockRecorder) CreateReport(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReport", reflect.TypeOf((*MockReportService)(nil).CreateReport), ctx, req)
}

// GetReportByID mocks base method.
func (m *MockReportService) GetReportByID(ctx context.Context, snowflakeID int64) (*report.ScheduledReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReportByID", ctx, snowflakeID)
	ret0, _ := ret[0].(*report.ScheduledReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReportByID indicates an expected call of GetReportByID.
func (mr *MockReportServiceMockRecorder) GetReportByID(ctx, snowflakeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReportByID", reflect.TypeOf((*MockReportService)(nil).GetReportByID), ctx, snowflakeID)
}

// ListReports mocks base method.
func (m *MockReportService) ListReports(ctx context.Context, req *report.ListReportsRequest) ([]report.ScheduledReport, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReports", ctx, req)
	ret0, _ := ret[0].([]report.ScheduledReport)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListReports indicates an expected call of ListReports.
func (mr *MockReportServiceMockRecorder) ListReports(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReports", reflect.TypeOf((*MockReportService)(nil).ListReports), ctx, req)
}

// UpdateReport mocks base method.
func (m *MockReportService) UpdateReport(ctx context.Context, snowflakeID int64, req *report.UpdateReportRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReport", ctx, snowflakeID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateReport indicates an expected call of UpdateReport.
func (mr *MockReportServiceMockRecorder) UpdateReport(ctx, snowflakeID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReport", reflect.TypeOf((*MockReportService)(nil).UpdateReport), ctx, snowflakeID, req)
}

// DeleteReport mocks base method.
func (m *MockReportService) DeleteReport(ctx context.Context, snowflakeID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteReport", ctx, snowflakeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteReport indicates an expected call of DeleteReport.
func (mr *MockReportServiceMockRecorder) DeleteReport(ctx, snowflakeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteReport", reflect.TypeOf((*MockReportService)(nil).DeleteReport), ctx, snowflakeID)
}

// GetPushRecords mocks base method.
func (m *MockReportService) GetPushRecords(ctx context.Context, req *report.GetPushRecordsRequest) ([]report.PushRecord, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPushRecords", ctx, req)
	ret0, _ := ret[0].([]report.PushRecord)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPushRecords indicates an expected call of GetPushRecords.
func (mr *MockReportServiceMockRecorder) GetPushRecords(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPushRecords", reflect.TypeOf((*MockReportService)(nil).GetPushRecords), ctx, req)
}
