// Code generated by MockGen. DO NOT EDIT.
// Package mocks provides mock implementations for repository interfaces.

package mocks

import (
	"context"
	"reflect"

	"jiufang/internal/model/dialog"
	"jiufang/internal/repository"

	"github.com/golang/mock/gomock"
)

// MockDialogRepository is a mock of DialogRepositoryInterface.
type MockDialogRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDialogRepositoryMockRecorder
}

// MockDialogRepositoryMockRecorder is the mock recorder for MockDialogRepository.
type MockDialogRepositoryMockRecorder struct {
	mock *MockDialogRepository
}

// NewMockDialogRepository creates a new mock instance.
func NewMockDialogRepository(ctrl *gomock.Controller) *MockDialogRepository {
	mock := &MockDialogRepository{ctrl: ctrl}
	mock.recorder = &MockDialogRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDialogRepository) EXPECT() *MockDialogRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDialogRepository) Create(ctx context.Context, session *dialog.DialogSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDialogRepositoryMockRecorder) Create(ctx, session interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDialogRepository)(nil).Create), ctx, session)
}

// GetByID mocks base method.
func (m *MockDialogRepository) GetByID(ctx context.Context, id uint) (*dialog.DialogSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*dialog.DialogSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDialogRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDialogRepository)(nil).GetByID), ctx, id)
}

// GetBySnowflakeID mocks base method.
func (m *MockDialogRepository) GetBySnowflakeID(ctx context.Context, snowflakeID string) (*dialog.DialogSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySnowflakeID", ctx, snowflakeID)
	ret0, _ := ret[0].(*dialog.DialogSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySnowflakeID indicates an expected call of GetBySnowflakeID.
func (mr *MockDialogRepositoryMockRecorder) GetBySnowflakeID(ctx, snowflakeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySnowflakeID", reflect.TypeOf((*MockDialogRepository)(nil).GetBySnowflakeID), ctx, snowflakeID)
}

// GetByUserID mocks base method.
func (m *MockDialogRepository) GetByUserID(ctx context.Context, userID uint, offset, limit int) ([]dialog.DialogSession, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID, offset, limit)
	ret0, _ := ret[0].([]dialog.DialogSession)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockDialogRepositoryMockRecorder) GetByUserID(ctx, userID, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockDialogRepository)(nil).GetByUserID), ctx, userID, offset, limit)
}

// GetActiveSessionsByUserID mocks base method.
func (m *MockDialogRepository) GetActiveSessionsByUserID(ctx context.Context, userID uint) ([]dialog.DialogSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveSessionsByUserID", ctx, userID)
	ret0, _ := ret[0].([]dialog.DialogSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveSessionsByUserID indicates an expected call of GetActiveSessionsByUserID.
func (mr *MockDialogRepositoryMockRecorder) GetActiveSessionsByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveSessionsByUserID", reflect.TypeOf((*MockDialogRepository)(nil).GetActiveSessionsByUserID), ctx, userID)
}

// Update mocks base method.
func (m *MockDialogRepository) Update(ctx context.Context, session *dialog.DialogSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDialogRepositoryMockRecorder) Update(ctx, session interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDialogRepository)(nil).Update), ctx, session)
}

// UpdateStatus mocks base method.
func (m *MockDialogRepository) UpdateStatus(ctx context.Context, id uint, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockDialogRepositoryMockRecorder) UpdateStatus(ctx, id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockDialogRepository)(nil).UpdateStatus), ctx, id, status)
}

// Delete mocks base method.
func (m *MockDialogRepository) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDialogRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDialogRepository)(nil).Delete), ctx, id)
}

// CloseSession mocks base method.
func (m *MockDialogRepository) CloseSession(ctx context.Context, snowflakeID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSession", ctx, snowflakeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSession indicates an expected call of CloseSession.
func (mr *MockDialogRepositoryMockRecorder) CloseSession(ctx, snowflakeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSession", reflect.TypeOf((*MockDialogRepository)(nil).CloseSession), ctx, snowflakeID)
}

// Ensure MockDialogRepository implements DialogRepositoryInterface
var _ repository.DialogRepositoryInterface = (*MockDialogRepository)(nil)
