// Code generated by MockGen. DO NOT EDIT.
// Source: jiufang/internal/infrastructure/cache/dialog_cache_interface.go

package mocks

import (
	"context"
	"reflect"

	"github.com/golang/mock/gomock"

	"jiufang/internal/model/dialog"
)

// MockDialogCache is a mock of DialogCacheInterface.
type MockDialogCache struct {
	ctrl     *gomock.Controller
	recorder *MockDialogCacheMockRecorder
}

// MockDialogCacheMockRecorder is the mock recorder for MockDialogCache.
type MockDialogCacheMockRecorder struct {
	mock *MockDialogCache
}

// NewMockDialogCache creates a new mock instance.
func NewMockDialogCache(ctrl *gomock.Controller) *MockDialogCache {
	mock := &MockDialogCache{ctrl: ctrl}
	mock.recorder = &MockDialogCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDialogCache) EXPECT() *MockDialogCacheMockRecorder {
	return m.recorder
}

// LoadContext mocks base method.
func (m *MockDialogCache) LoadContext(ctx context.Context, sessionID string) (*dialog.DialogContext, error) {
	ret := m.ctrl.Call(m, "LoadContext", ctx, sessionID)
	ret0, _ := ret[0].(*dialog.DialogContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadContext indicates an expected call of LoadContext.
func (mr *MockDialogCacheMockRecorder) LoadContext(ctx, sessionID interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadContext", reflect.TypeOf((*MockDialogCache)(nil).LoadContext), ctx, sessionID)
}

// SaveContext mocks base method.
func (m *MockDialogCache) SaveContext(ctx context.Context, context *dialog.DialogContext) error {
	ret := m.ctrl.Call(m, "SaveContext", ctx, context)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveContext indicates an expected call of SaveContext.
func (mr *MockDialogCacheMockRecorder) SaveContext(ctx, context interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveContext", reflect.TypeOf((*MockDialogCache)(nil).SaveContext), ctx, context)
}

// ClearContext mocks base method.
func (m *MockDialogCache) ClearContext(ctx context.Context, sessionID string) error {
	ret := m.ctrl.Call(m, "ClearContext", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearContext indicates an expected call of ClearContext.
func (mr *MockDialogCacheMockRecorder) ClearContext(ctx, sessionID interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearContext", reflect.TypeOf((*MockDialogCache)(nil).ClearContext), ctx, sessionID)
}