// Code generated by MockGen. DO NOT EDIT.
// Package mocks provides mock implementations for repository interfaces.

package mocks

import (
	"context"
	"reflect"

	"jiufang/internal/model/query"
	"jiufang/internal/repository"

	"github.com/golang/mock/gomock"
)

// MockQueryRepository is a mock of QueryRepositoryInterface.
type MockQueryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockQueryRepositoryMockRecorder
}

// MockQueryRepositoryMockRecorder is the mock recorder for MockQueryRepository.
type MockQueryRepositoryMockRecorder struct {
	mock *MockQueryRepository
}

// NewMockQueryRepository creates a new mock instance.
func NewMockQueryRepository(ctrl *gomock.Controller) *MockQueryRepository {
	mock := &MockQueryRepository{ctrl: ctrl}
	mock.recorder = &MockQueryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryRepository) EXPECT() *MockQueryRepositoryMockRecorder {
	return m.recorder
}

// CreateQuerySession mocks base method.
func (m *MockQueryRepository) CreateQuerySession(ctx context.Context, session *query.QuerySession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateQuerySession", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateQuerySession indicates an expected call of CreateQuerySession.
func (mr *MockQueryRepositoryMockRecorder) CreateQuerySession(ctx, session interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateQuerySession", reflect.TypeOf((*MockQueryRepository)(nil).CreateQuerySession), ctx, session)
}

// GetQuerySessionByID mocks base method.
func (m *MockQueryRepository) GetQuerySessionByID(ctx context.Context, id uint) (*query.QuerySession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuerySessionByID", ctx, id)
	ret0, _ := ret[0].(*query.QuerySession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuerySessionByID indicates an expected call of GetQuerySessionByID.
func (mr *MockQueryRepositoryMockRecorder) GetQuerySessionByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuerySessionByID", reflect.TypeOf((*MockQueryRepository)(nil).GetQuerySessionByID), ctx, id)
}

// GetQuerySessionBySnowflakeID mocks base method.
func (m *MockQueryRepository) GetQuerySessionBySnowflakeID(ctx context.Context, snowflakeID int64) (*query.QuerySession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuerySessionBySnowflakeID", ctx, snowflakeID)
	ret0, _ := ret[0].(*query.QuerySession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuerySessionBySnowflakeID indicates an expected call of GetQuerySessionBySnowflakeID.
func (mr *MockQueryRepositoryMockRecorder) GetQuerySessionBySnowflakeID(ctx, snowflakeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuerySessionBySnowflakeID", reflect.TypeOf((*MockQueryRepository)(nil).GetQuerySessionBySnowflakeID), ctx, snowflakeID)
}

// GetQuerySessionsByUserID mocks base method.
func (m *MockQueryRepository) GetQuerySessionsByUserID(ctx context.Context, userID int64, offset, limit int) ([]query.QuerySession, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuerySessionsByUserID", ctx, userID, offset, limit)
	ret0, _ := ret[0].([]query.QuerySession)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetQuerySessionsByUserID indicates an expected call of GetQuerySessionsByUserID.
func (mr *MockQueryRepositoryMockRecorder) GetQuerySessionsByUserID(ctx, userID, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuerySessionsByUserID", reflect.TypeOf((*MockQueryRepository)(nil).GetQuerySessionsByUserID), ctx, userID, offset, limit)
}

// CloseQuerySession mocks base method.
func (m *MockQueryRepository) CloseQuerySession(ctx context.Context, snowflakeID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseQuerySession", ctx, snowflakeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseQuerySession indicates an expected call of CloseQuerySession.
func (mr *MockQueryRepositoryMockRecorder) CloseQuerySession(ctx, snowflakeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseQuerySession", reflect.TypeOf((*MockQueryRepository)(nil).CloseQuerySession), ctx, snowflakeID)
}

// CreateQueryRecord mocks base method.
func (m *MockQueryRepository) CreateQueryRecord(ctx context.Context, record *query.QueryRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateQueryRecord", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateQueryRecord indicates an expected call of CreateQueryRecord.
func (mr *MockQueryRepositoryMockRecorder) CreateQueryRecord(ctx, record interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateQueryRecord", reflect.TypeOf((*MockQueryRepository)(nil).CreateQueryRecord), ctx, record)
}

// GetQueryRecordByID mocks base method.
func (m *MockQueryRepository) GetQueryRecordByID(ctx context.Context, id uint) (*query.QueryRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQueryRecordByID", ctx, id)
	ret0, _ := ret[0].(*query.QueryRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQueryRecordByID indicates an expected call of GetQueryRecordByID.
func (mr *MockQueryRepositoryMockRecorder) GetQueryRecordByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueryRecordByID", reflect.TypeOf((*MockQueryRepository)(nil).GetQueryRecordByID), ctx, id)
}

// GetQueryRecordBySnowflakeID mocks base method.
func (m *MockQueryRepository) GetQueryRecordBySnowflakeID(ctx context.Context, snowflakeID int64) (*query.QueryRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQueryRecordBySnowflakeID", ctx, snowflakeID)
	ret0, _ := ret[0].(*query.QueryRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQueryRecordBySnowflakeID indicates an expected call of GetQueryRecordBySnowflakeID.
func (mr *MockQueryRepositoryMockRecorder) GetQueryRecordBySnowflakeID(ctx, snowflakeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueryRecordBySnowflakeID", reflect.TypeOf((*MockQueryRepository)(nil).GetQueryRecordBySnowflakeID), ctx, snowflakeID)
}

// GetQueryRecordsByUserID mocks base method.
func (m *MockQueryRepository) GetQueryRecordsByUserID(ctx context.Context, userID int64, offset, limit int, startTime, endTime string, status string) ([]query.QueryRecord, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQueryRecordsByUserID", ctx, userID, offset, limit, startTime, endTime, status)
	ret0, _ := ret[0].([]query.QueryRecord)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetQueryRecordsByUserID indicates an expected call of GetQueryRecordsByUserID.
func (mr *MockQueryRepositoryMockRecorder) GetQueryRecordsByUserID(ctx, userID, offset, limit, startTime, endTime, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueryRecordsByUserID", reflect.TypeOf((*MockQueryRepository)(nil).GetQueryRecordsByUserID), ctx, userID, offset, limit, startTime, endTime, status)
}

// GetQueryRecordsBySessionID mocks base method.
func (m *MockQueryRepository) GetQueryRecordsBySessionID(ctx context.Context, sessionID int64) ([]query.QueryRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQueryRecordsBySessionID", ctx, sessionID)
	ret0, _ := ret[0].([]query.QueryRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQueryRecordsBySessionID indicates an expected call of GetQueryRecordsBySessionID.
func (mr *MockQueryRepositoryMockRecorder) GetQueryRecordsBySessionID(ctx, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueryRecordsBySessionID", reflect.TypeOf((*MockQueryRepository)(nil).GetQueryRecordsBySessionID), ctx, sessionID)
}

// DeleteQueryRecord mocks base method.
func (m *MockQueryRepository) DeleteQueryRecord(ctx context.Context, snowflakeID int64, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteQueryRecord", ctx, snowflakeID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteQueryRecord indicates an expected call of DeleteQueryRecord.
func (mr *MockQueryRepositoryMockRecorder) DeleteQueryRecord(ctx, snowflakeID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteQueryRecord", reflect.TypeOf((*MockQueryRepository)(nil).DeleteQueryRecord), ctx, snowflakeID, userID)
}

// CreateFavorite mocks base method.
func (m *MockQueryRepository) CreateFavorite(ctx context.Context, favorite *query.Favorite) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFavorite", ctx, favorite)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFavorite indicates an expected call of CreateFavorite.
func (mr *MockQueryRepositoryMockRecorder) CreateFavorite(ctx, favorite interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFavorite", reflect.TypeOf((*MockQueryRepository)(nil).CreateFavorite), ctx, favorite)
}

// GetFavoriteByID mocks base method.
func (m *MockQueryRepository) GetFavoriteByID(ctx context.Context, id uint) (*query.Favorite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFavoriteByID", ctx, id)
	ret0, _ := ret[0].(*query.Favorite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFavoriteByID indicates an expected call of GetFavoriteByID.
func (mr *MockQueryRepositoryMockRecorder) GetFavoriteByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavoriteByID", reflect.TypeOf((*MockQueryRepository)(nil).GetFavoriteByID), ctx, id)
}

// GetFavoriteBySnowflakeID mocks base method.
func (m *MockQueryRepository) GetFavoriteBySnowflakeID(ctx context.Context, snowflakeID int64) (*query.Favorite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFavoriteBySnowflakeID", ctx, snowflakeID)
	ret0, _ := ret[0].(*query.Favorite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFavoriteBySnowflakeID indicates an expected call of GetFavoriteBySnowflakeID.
func (mr *MockQueryRepositoryMockRecorder) GetFavoriteBySnowflakeID(ctx, snowflakeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavoriteBySnowflakeID", reflect.TypeOf((*MockQueryRepository)(nil).GetFavoriteBySnowflakeID), ctx, snowflakeID)
}

// GetFavoritesByUserID mocks base method.
func (m *MockQueryRepository) GetFavoritesByUserID(ctx context.Context, userID int64, offset, limit int, name string) ([]query.Favorite, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFavoritesByUserID", ctx, userID, offset, limit, name)
	ret0, _ := ret[0].([]query.Favorite)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetFavoritesByUserID indicates an expected call of GetFavoritesByUserID.
func (mr *MockQueryRepositoryMockRecorder) GetFavoritesByUserID(ctx, userID, offset, limit, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavoritesByUserID", reflect.TypeOf((*MockQueryRepository)(nil).GetFavoritesByUserID), ctx, userID, offset, limit, name)
}

// DeleteFavorite mocks base method.
func (m *MockQueryRepository) DeleteFavorite(ctx context.Context, snowflakeID int64, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFavorite", ctx, snowflakeID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFavorite indicates an expected call of DeleteFavorite.
func (mr *MockQueryRepositoryMockRecorder) DeleteFavorite(ctx, snowflakeID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFavorite", reflect.TypeOf((*MockQueryRepository)(nil).DeleteFavorite), ctx, snowflakeID, userID)
}

// IsFavoriteNameExists mocks base method.
func (m *MockQueryRepository) IsFavoriteNameExists(ctx context.Context, userID int64, name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFavoriteNameExists", ctx, userID, name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsFavoriteNameExists indicates an expected call of IsFavoriteNameExists.
func (mr *MockQueryRepositoryMockRecorder) IsFavoriteNameExists(ctx, userID, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFavoriteNameExists", reflect.TypeOf((*MockQueryRepository)(nil).IsFavoriteNameExists), ctx, userID, name)
}

// Ensure MockQueryRepository implements QueryRepositoryInterface
var _ repository.QueryRepositoryInterface = (*MockQueryRepository)(nil)
