// Code generated by MockGen. DO NOT EDIT.
// Package mocks provides mock implementations for repository interfaces.

package mocks

import (
	"context"
	"reflect"

	"jiufang/internal/model/dialog"
	"jiufang/internal/repository"

	"github.com/golang/mock/gomock"
)

// MockDialogFavoriteRepository is a mock of DialogFavoriteRepositoryInterface.
type MockDialogFavoriteRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDialogFavoriteRepositoryMockRecorder
}

// MockDialogFavoriteRepositoryMockRecorder is the mock recorder for MockDialogFavoriteRepository.
type MockDialogFavoriteRepositoryMockRecorder struct {
	mock *MockDialogFavoriteRepository
}

// NewMockDialogFavoriteRepository creates a new mock instance.
func NewMockDialogFavoriteRepository(ctrl *gomock.Controller) *MockDialogFavoriteRepository {
	mock := &MockDialogFavoriteRepository{ctrl: ctrl}
	mock.recorder = &MockDialogFavoriteRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDialogFavoriteRepository) EXPECT() *MockDialogFavoriteRepositoryMockRecorder {
	return m.recorder
}

// CreateDialogFavorite mocks base method.
func (m *MockDialogFavoriteRepository) CreateDialogFavorite(ctx context.Context, favorite *dialog.DialogFavorite) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDialogFavorite", ctx, favorite)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDialogFavorite indicates an expected call of CreateDialogFavorite.
func (mr *MockDialogFavoriteRepositoryMockRecorder) CreateDialogFavorite(ctx, favorite interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDialogFavorite", reflect.TypeOf((*MockDialogFavoriteRepository)(nil).CreateDialogFavorite), ctx, favorite)
}

// GetDialogFavoriteByID mocks base method.
func (m *MockDialogFavoriteRepository) GetDialogFavoriteByID(ctx context.Context, id uint) (*dialog.DialogFavorite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDialogFavoriteByID", ctx, id)
	ret0, _ := ret[0].(*dialog.DialogFavorite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDialogFavoriteByID indicates an expected call of GetDialogFavoriteByID.
func (mr *MockDialogFavoriteRepositoryMockRecorder) GetDialogFavoriteByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDialogFavoriteByID", reflect.TypeOf((*MockDialogFavoriteRepository)(nil).GetDialogFavoriteByID), ctx, id)
}

// GetDialogFavoriteBySnowflakeID mocks base method.
func (m *MockDialogFavoriteRepository) GetDialogFavoriteBySnowflakeID(ctx context.Context, snowflakeID int64) (*dialog.DialogFavorite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDialogFavoriteBySnowflakeID", ctx, snowflakeID)
	ret0, _ := ret[0].(*dialog.DialogFavorite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDialogFavoriteBySnowflakeID indicates an expected call of GetDialogFavoriteBySnowflakeID.
func (mr *MockDialogFavoriteRepositoryMockRecorder) GetDialogFavoriteBySnowflakeID(ctx, snowflakeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDialogFavoriteBySnowflakeID", reflect.TypeOf((*MockDialogFavoriteRepository)(nil).GetDialogFavoriteBySnowflakeID), ctx, snowflakeID)
}

// GetDialogFavoritesByUserID mocks base method.
func (m *MockDialogFavoriteRepository) GetDialogFavoritesByUserID(ctx context.Context, userID int64, offset, limit int) ([]dialog.DialogFavorite, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDialogFavoritesByUserID", ctx, userID, offset, limit)
	ret0, _ := ret[0].([]dialog.DialogFavorite)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetDialogFavoritesByUserID indicates an expected call of GetDialogFavoritesByUserID.
func (mr *MockDialogFavoriteRepositoryMockRecorder) GetDialogFavoritesByUserID(ctx, userID, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDialogFavoritesByUserID", reflect.TypeOf((*MockDialogFavoriteRepository)(nil).GetDialogFavoritesByUserID), ctx, userID, offset, limit)
}

// DeleteDialogFavorite mocks base method.
func (m *MockDialogFavoriteRepository) DeleteDialogFavorite(ctx context.Context, snowflakeID int64, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDialogFavorite", ctx, snowflakeID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDialogFavorite indicates an expected call of DeleteDialogFavorite.
func (mr *MockDialogFavoriteRepositoryMockRecorder) DeleteDialogFavorite(ctx, snowflakeID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDialogFavorite", reflect.TypeOf((*MockDialogFavoriteRepository)(nil).DeleteDialogFavorite), ctx, snowflakeID, userID)
}

// IsDialogFavoriteExists mocks base method.
func (m *MockDialogFavoriteRepository) IsDialogFavoriteExists(ctx context.Context, userID int64, dialogSessionID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDialogFavoriteExists", ctx, userID, dialogSessionID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsDialogFavoriteExists indicates an expected call of IsDialogFavoriteExists.
func (mr *MockDialogFavoriteRepositoryMockRecorder) IsDialogFavoriteExists(ctx, userID, dialogSessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDialogFavoriteExists", reflect.TypeOf((*MockDialogFavoriteRepository)(nil).IsDialogFavoriteExists), ctx, userID, dialogSessionID)
}

// GetDialogFavoriteByUserAndSession mocks base method.
func (m *MockDialogFavoriteRepository) GetDialogFavoriteByUserAndSession(ctx context.Context, userID int64, dialogSessionID int64) (*dialog.DialogFavorite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDialogFavoriteByUserAndSession", ctx, userID, dialogSessionID)
	ret0, _ := ret[0].(*dialog.DialogFavorite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDialogFavoriteByUserAndSession indicates an expected call of GetDialogFavoriteByUserAndSession.
func (mr *MockDialogFavoriteRepositoryMockRecorder) GetDialogFavoriteByUserAndSession(ctx, userID, dialogSessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDialogFavoriteByUserAndSession", reflect.TypeOf((*MockDialogFavoriteRepository)(nil).GetDialogFavoriteByUserAndSession), ctx, userID, dialogSessionID)
}

// Ensure MockDialogFavoriteRepository implements DialogFavoriteRepositoryInterface
var _ repository.DialogFavoriteRepositoryInterface = (*MockDialogFavoriteRepository)(nil)